//! System tray icon + native context menu (DESIGN.md §3). Static glyph (no tray
//! animation — the HUD carries the live signal). Icon swaps light/dark to match
//! the taskbar; menu shows the current binding and the Start/Stop label.

use std::sync::mpsc::Sender;
use tauri::{
    image::Image,
    menu::{IsMenuItem, Menu, MenuItem, PredefinedMenuItem},
    tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent},
    AppHandle, Emitter, Manager,
};

use crate::types::{Config, CoordMsg};

/// Tray icon/menu state. Defined here (shell owns the tray); the coordinator's
/// `Effects::tray_state` takes `crate::tray::TrayState`.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum TrayState {
    Idle,
    Recording,
    Error,
}

// 16px tray glyphs as raw RGBA (generated by scripts/gen-icons.mjs), loaded via
// Image::new — no image-png feature, no runtime decode. *-light = light glyph
// for a dark taskbar; *-dark = dark glyph for a light taskbar.
const ICON_SIZE: u32 = 16;
const IDLE_L: &[u8] = include_bytes!("../resources/tray-idle-light.rgba");
const IDLE_D: &[u8] = include_bytes!("../resources/tray-idle-dark.rgba");
const REC_L: &[u8] = include_bytes!("../resources/tray-rec-light.rgba");
const REC_D: &[u8] = include_bytes!("../resources/tray-rec-dark.rgba");
const ERR_L: &[u8] = include_bytes!("../resources/tray-err-light.rgba");
const ERR_D: &[u8] = include_bytes!("../resources/tray-err-dark.rgba");

pub struct Tray {
    icon: TrayIcon,
    app: AppHandle,
    recording: bool,
    mic_error: bool,
    paste_enabled: bool, // a transcription is held for PasteLast (DESIGN §5.7)
    binding: String,     // human display, e.g. "Ctrl + Alt + Space"
}

pub fn init(app: &AppHandle, tx: Sender<CoordMsg>, cfg: &Config) -> tauri::Result<Tray> {
    let binding = format_binding(&cfg.hotkey);
    let menu = build_menu(app, false, false, &binding)?;
    let tx_menu = tx.clone();
    let icon = TrayIconBuilder::new()
        .icon(load_icon(false, false))
        .tooltip("DICTUM")
        .menu(&menu)
        .show_menu_on_left_click(false) // left-click toggles dictation, not the menu
        .on_menu_event(move |app, ev| handle_menu(app, ev.id.as_ref(), &tx_menu))
        .on_tray_icon_event(move |tray, ev| handle_tray_event(tray, ev, &tx))
        .build(app)?;
    Ok(Tray {
        icon,
        app: app.clone(),
        recording: false,
        mic_error: false,
        paste_enabled: false,
        binding,
    })
}

impl Tray {
    pub fn set_state(&mut self, state: TrayState) {
        let (rec, err) = match state {
            TrayState::Idle => (false, false),
            TrayState::Recording => (true, false),
            TrayState::Error => (false, true),
        };
        if rec == self.recording && err == self.mic_error {
            return;
        }
        self.recording = rec;
        self.mic_error = err;
        let _ = self.icon.set_icon(Some(load_icon(rec, err)));
        self.refresh_menu();
    }

    /// Refresh the accelerator text after a hotkey rebind.
    pub fn set_binding(&mut self, chord: &str) {
        self.binding = format_binding(chord);
        self.refresh_menu();
    }

    /// Enable "Paste last transcription" once a take is held (DESIGN §5.7).
    pub fn set_paste_enabled(&mut self, on: bool) {
        if on == self.paste_enabled {
            return;
        }
        self.paste_enabled = on;
        self.refresh_menu();
    }

    fn refresh_menu(&self) {
        if let Ok(menu) = build_menu(&self.app, self.recording, self.paste_enabled, &self.binding) {
            let _ = self.icon.set_menu(Some(menu));
        }
    }
}

/// Show the main window and switch it to `view` ("tape" | "setup").
fn open_main(app: &AppHandle, view: &str) {
    if let Some(w) = app.get_webview_window("main") {
        let _ = w.unminimize();
        let _ = w.show();
        let _ = w.set_focus();
    }
    let _ = app.emit("nav://view", view);
}

fn handle_menu(app: &AppHandle, id: &str, tx: &Sender<CoordMsg>) {
    match id {
        "toggle" => { let _ = tx.send(CoordMsg::ToggleDictation); }
        "paste_last" => { let _ = tx.send(CoordMsg::PasteLast); }
        "history" => open_main(app, "tape"),
        "settings" => open_main(app, "setup"),
        "quit" => app.exit(0),
        _ => {}
    }
}

fn handle_tray_event(tray: &TrayIcon, ev: TrayIconEvent, tx: &Sender<CoordMsg>) {
    match ev {
        // ponytail: a double-click also emits two single-clicks, so it toggles
        // twice then opens the tape. Acceptable v1 tray behavior; de-dupe with a
        // click timer only if it annoys.
        TrayIconEvent::Click { button: MouseButton::Left, button_state: MouseButtonState::Up, .. } => {
            let _ = tx.send(CoordMsg::ToggleDictation);
        }
        TrayIconEvent::DoubleClick { button: MouseButton::Left, .. } => {
            open_main(tray.app_handle(), "tape");
        }
        _ => {}
    }
}

/// DESIGN §5.7 item list, verbatim. The OS draws the menu.
fn build_menu(app: &AppHandle, recording: bool, paste_enabled: bool, binding: &str) -> tauri::Result<Menu<tauri::Wry>> {
    let toggle_label = if recording { "Stop dictation" } else { "Start dictation" };
    // Windows native menus right-align text after a tab as the accelerator column.
    let toggle = MenuItem::with_id(app, "toggle", format!("{toggle_label}\t{binding}"), true, None::<&str>)?;
    let paste = MenuItem::with_id(app, "paste_last", "Paste last transcription", paste_enabled, None::<&str>)?;
    let sep_a = PredefinedMenuItem::separator(app)?;
    let history = MenuItem::with_id(app, "history", "History", true, None::<&str>)?;
    let settings = MenuItem::with_id(app, "settings", "Settings", true, None::<&str>)?;
    let sep_b = PredefinedMenuItem::separator(app)?;
    let quit = MenuItem::with_id(app, "quit", "Quit Dictum", true, None::<&str>)?;

    let items: Vec<&dyn IsMenuItem<tauri::Wry>> =
        vec![&toggle, &paste, &sep_a, &history, &settings, &sep_b, &quit];
    Menu::with_items(app, &items)
}

fn load_icon(recording: bool, mic_error: bool) -> Image<'static> {
    let light_taskbar = system_uses_light_theme();
    let bytes = match (mic_error, recording, light_taskbar) {
        (true, _, true) => ERR_D,
        (true, _, false) => ERR_L,
        (_, true, true) => REC_D,
        (_, true, false) => REC_L,
        (_, _, true) => IDLE_D,
        (_, _, false) => IDLE_L,
    };
    Image::new(bytes, ICON_SIZE, ICON_SIZE)
}

/// true => light taskbar (use the dark glyph). Defaults to dark taskbar on any
/// registry read failure.
fn system_uses_light_theme() -> bool {
    windows_registry::CURRENT_USER
        .open(r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize")
        .and_then(|k| k.get_u32("SystemUsesLightTheme"))
        .map(|v| v == 1)
        .unwrap_or(false)
}

/// Chord in global-shortcut syntax -> menu accelerator display, e.g.
/// "Ctrl+Super" -> "Ctrl + Win", "Ctrl+Shift+KeyD" -> "Ctrl + Shift + D".
fn format_binding(chord: &str) -> String {
    chord
        .split('+')
        .map(|p| {
            let p = p.trim();
            match p {
                "Super" | "Meta" | "Cmd" | "Command" | "Win" => "Win".to_string(),
                "Control" | "Ctrl" | "CmdOrCtrl" => "Ctrl".to_string(),
                "Alt" | "Option" => "Alt".to_string(),
                "Shift" => "Shift".to_string(),
                _ if p.len() == 4 && p.starts_with("Key") => p[3..].to_string(),
                _ if p.len() == 6 && p.starts_with("Digit") => p[5..].to_string(),
                _ => p.to_string(),
            }
        })
        .collect::<Vec<_>>()
        .join(" + ")
}

#[cfg(test)]
mod tests {
    use super::format_binding;

    #[test]
    fn formats_default_binding() {
        assert_eq!(format_binding("Ctrl+Super"), "Ctrl + Win");
    }

    #[test]
    fn strips_key_and_digit_prefixes() {
        assert_eq!(format_binding("Ctrl+Shift+KeyD"), "Ctrl + Shift + D");
        assert_eq!(format_binding("Alt+Digit1"), "Alt + 1");
    }

    #[test]
    fn passes_through_named_keys() {
        assert_eq!(format_binding("Ctrl+Space"), "Ctrl + Space");
    }
}
